export const HASHTAG_MENU = [
    '가족과함께',
    '베스트프렌즈',
    '연인과의시간',
    '즐거운순간',
    '도전',
    '소소한두려움',
    '우울탈출',
    '혼자서도괜찮아',
    '행복한시간',
    '용기있는도전',
    '특별한순간',
    '감정여행',
    '나를위한여행',
];

export const COUNTRY_OPTIONS = [
    { emoji: '🇰🇷', name: '한국' },
    { emoji: '🇯🇵', name: '일본' },
    { emoji: '🇺🇸', name: '미국' },
    { emoji: '🇨🇳', name: '중국' },
    { emoji: '🇮🇳', name: '인도' },
    { emoji: '🇬🇧', name: '영국' },
    { emoji: '🇩🇪', name: '독일' },
    { emoji: '🇫🇷', name: '프랑스' },
    { emoji: '🇮🇹', name: '이탈리아' },
    { emoji: '🇧🇷', name: '브라질' },
    { emoji: '🇷🇺', name: '러시아' },
    { emoji: '🇨🇦', name: '캐나다' },
    { emoji: '🇦🇺', name: '호주' },
    { emoji: '🇲🇽', name: '멕시코' },
    { emoji: '🇪🇸', name: '스페인' },
    { emoji: '🇦🇷', name: '아르헨티나' },
    { emoji: '🇿🇦', name: '남아프리카 공화국' },
    { emoji: '🇳🇬', name: '나이지리아' },
    { emoji: '🇸🇦', name: '사우디아라비아' },
    { emoji: '🇹🇷', name: '터키' },
    { emoji: '🇮🇩', name: '인도네시아' },
    { emoji: '🇹🇭', name: '태국' },
    { emoji: '🇻🇳', name: '베트남' },
    { emoji: '🇪🇬', name: '이집트' },
    { emoji: '🇵🇭', name: '필리핀' },
    { emoji: '🇵🇰', name: '파키스탄' },
    { emoji: '🇧🇩', name: '방글라데시' },
    { emoji: '🇵🇱', name: '폴란드' },
    { emoji: '🇳🇱', name: '네덜란드' },
    { emoji: '🇸🇪', name: '스웨덴' },
    { emoji: '🇨🇭', name: '스위스' },
    { emoji: '🇵🇹', name: '포르투갈' },
];

export const NEW_COUNTRY = {
    TITLE: '여행 제목',
    TITLE_PLACEHOLDER: '여행 제목을 입력하세요',
    COUNTRY: '여행 국가',
    COUNTRY_DEFAULT: '국가를 선택하세요',
    START_DATE: '시작 날짜',
    END_DATE: '종료 날짜',
    HASHTAG: '해시태그',
};
