name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-nm-

            - name: Install dependencies
              run: yarn install --frozen-lockfile --legacy-peer-deps

            - name: Install Vercel CLI
              if: github.repository == 'marista-dev/trip-tyche_FE'
              run: npm install -g vercel@latest

            - name: Type checking
              run: npx tsc --noEmit -p tsconfig.app.json

            - name: Pull Vercel environment (Production)
              if: github.repository == 'marista-dev/trip-tyche_FE' && github.ref == 'refs/heads/main'
              run: vercel pull --yes --environment=production

            - name: Pull Vercel environment (Preview)
              if: github.repository == 'marista-dev/trip-tyche_FE' && github.ref == 'refs/heads/develop'
              run: vercel pull --yes --environment=preview

            - name: Build (Production)
              if: github.repository == 'marista-dev/trip-tyche_FE' && github.ref == 'refs/heads/main'
              run: vercel build --prod

            - name: Build (Preview)
              if: github.repository == 'marista-dev/trip-tyche_FE' && github.ref == 'refs/heads/develop'
              run: vercel build

            - name: Deploy (Production)
              if: github.repository == 'marista-dev/trip-tyche_FE' && github.ref == 'refs/heads/main'
              run: vercel deploy --prebuilt --prod

            - name: Deploy (Preview)
              if: github.repository == 'marista-dev/trip-tyche_FE' && github.ref == 'refs/heads/develop'
              run: vercel deploy --prebuilt
