name: CI/CD Pipeline

on:
    push:
        branches:
            - main
            - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      ~/.cache/Cypress
                  key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-nm-

            - name: Install dependencies
              run: yarn install --frozen-lockfile --legacy-peer-deps

            - name: Install Vercel CLI
              run: npm install -g vercel@latest

            - name: Type checking
              run: yarn tsc --noEmit

            - name: Pull Vercel environment (Production)
              if: github.ref == 'refs/heads/main'
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Pull Vercel environment (Preview)
              if: github.ref == 'refs/heads/develop'
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build (Production)
              if: github.ref == 'refs/heads/main'
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build (Preview)
              if: github.ref == 'refs/heads/develop'
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy (Production)
              if: github.ref == 'refs/heads/main'
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy (Preview)
              if: github.ref == 'refs/heads/develop'
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
